// src/styles.js
import { StyleSheet } from 'react-native';

export const lightTheme = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0e4ff', 
    padding: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#6a4c9c', 
    paddingBottom: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#6a4c9c', 
    fontFamily: 'Poppins-Bold', 
    letterSpacing: 1,  
  },
  addTaskContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  addTaskInput: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#e1bee7', 
    padding: 15,
    marginRight: 10,
    color: '#6a4c9c', 
    fontFamily: 'Poppins-Regular', 
    borderRadius: 10, 
  },
  addTaskButton: {
    backgroundColor: '#6a4c9c', 
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 30, 
    alignItems: 'center',
  },
  addTaskButtonText: {
    color: '#fff', 
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'Poppins-Bold', 
  },
  filterContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 20,
  },
  filterButton: {
    padding: 12,
    borderRadius: 20, 
    marginHorizontal: 10,
    backgroundColor: '#6a4c9c', 
  },
  filterButtonActive: {
    backgroundColor: '#9b4f96', 
  },
  filterText: {
    color: '#fff',
    fontFamily: 'Poppins-Regular',
  },
  taskItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    marginBottom: 15,
    backgroundColor: '#fff',
    borderRadius: 15, 
    shadowColor: '#000', 
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  taskTitle: {
    flex: 1,
    marginLeft: 10,
    fontSize: 18,
    color: '#6a4c9c', 
    fontFamily: 'Poppins-Regular',
  },
  taskInput: {
    flex: 1,
    marginLeft: 10,
    borderWidth: 2,
    borderColor: '#e1bee7',
    padding: 10,
    color: '#6a4c9c',
    fontFamily: 'Poppins-Regular',
    borderRadius: 10,
  },
});

export const darkTheme = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121212', 
    padding: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#6a4c9c', 
    paddingBottom: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
    fontFamily: 'Poppins-Bold', 
    letterSpacing: 1,
  },
  addTaskContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  addTaskInput: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#e1bee7', 
    padding: 15,
    marginRight: 10,
    color: '#fff', 
    fontFamily: 'Poppins-Regular',
    borderRadius: 10, 
  },
  addTaskButton: {
    backgroundColor: '#6a4c9c',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 30, 
    alignItems: 'center',
  },
  addTaskButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'Poppins-Bold',
  },
  filterContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 20,
  },
  filterButton: {
    padding: 12,
    borderRadius: 20,
    marginHorizontal: 10,
    backgroundColor: '#6a4c9c', 
  },
  filterButtonActive: {
    backgroundColor: '#9b4f96', 
  },
  filterText: {
    color: '#fff', 
    fontFamily: 'Poppins-Regular',
  },
  taskItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    marginBottom: 15,
    backgroundColor: '#333',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  taskTitle: {
    flex: 1,
    marginLeft: 10,
    fontSize: 18,
    color: '#fff', 
    fontFamily: 'Poppins-Regular',
  },
  taskInput: {
    flex: 1,
    marginLeft: 10,
    borderWidth: 2,
    borderColor: '#e1bee7',
    padding: 10,
    color: '#fff',
    fontFamily: 'Poppins-Regular',
    borderRadius: 10,
  },
});
